# Main composition file for TACACS+ Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

version: '3'
services:
  tacacasplus:
    container_name: tacacasplus
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "49:49"
    volumes:
      - "./config/tac_plus.cfg:/etc/tac_plus/tac_plus.cfg"
      - "./log/tacacs.log:/var/log/tacacs.log"

  tacacsdb:
    container_name: tacacsdb
    restart: always
    build:
      context: ./db/  
      dockerfile: Dockerfile
    ports:
      - "3308:3306"
    env_file:
      - ./env/.env_tacacsdb
    volumes:
      - "./db/db_data:/var/lib/mysql"

  connector:
    container_name: connector
    build:
      context: ./app/
      dockerfile: Dockerfile
    depends_on:
      - tacacasplus
      - tacacsdb
    volumes:
      - "./app:/app"
      - "./log:/applog"