# Dockerfile: Defines container specifications to startup and run.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

FROM lfkeitel/tacacs_plus:alpine-202104181633

RUN touch /var/log/tacacs.log

RUN chmod 777 /var/log/tacacs.log